#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
mkdir Test
cd Test
touch a b c
echo aaa > a
echo bbb > b
echo ccc > c
mkdir subdir
cd subdir
touch aa bb cc
echo AAA > aa
echo BBB > bb
echo CCC > cc
exit 0
