//
// Created by Leo Pilcher on 8/29/26.
//

#ifndef SAVESTUFF_COMMANDS_H
#define SAVESTUFF_COMMANDS_H

enum Commands {
    COMMANDS_HELP_GENERAL,
    COMMANDS_HELP_VERSION,
    COMMANDS_HELP_BACKUP,
    COMMANDS_HELP_RESTORE,
    COMMANDS_VERSION,
    COMMANDS_BACKUP,
    COMMANDS_RESTORE,
    COMMANDS_NONE
};

#endif //SAVESTUFF_COMMANDS_H
